name: Test git submodule

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        # with:
        #   submodules: true
        #   token: ${{ secrets.PAT }}

      - name: build
        shell: bash
        run: |
          TOKEN=${{ secrets.PAT }}
          git submodule update --init --recursive --config "submodule.git-sub-module.url=https://$TOKEN@github.com/sudarsana-reddy/git-sub-module.git"
          mvn -B verify --file pom.xml     
