name: Test git submodule

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.PAT }}

      - name: sync code to github-with-sub-complete-repo
        shell: bash
        env:
          TOKEN: ${{ secrets.PAT }}
        run: |
          ls -ltr
          git rm --cached .gitmodules
          rm -f .gitmodules
          ls -ltr
          cd git-sub-module
          ls -ltr
          echo "Setting remote add"
          git remote add adobe https://$TOKEN@github.com/sudarsana-reddy/github-with-sub-complete-repo.git
          echo "set username"
          git config credential.username sudarsana.ala@gmail.com
          echo "set password"
          git config credential.helper "!echo password=${{ secrets.PAT }}; echo"
          echo "show remote urls"
          git remote -v
          echo "checking out main"
          git checkout main
          echo "pull the chages"
          git pull
          echo "git status"
          git status
          echo "push the changes to remote"
          git push -u adobe main --force
    
      - name: build
        shell: bash
        run: |
          # TOKEN=${{ secrets.PAT }}
          # git -c submodule.git-sub-module.url=https://$TOKEN@github.com/sudarsana-reddy/git-sub-module.git submodule update --init --recursive
          mvn -B verify --file pom.xml
