name: Test git submodule

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.PAT }}
          # persist-credentials: false

      - name: sync code to github-with-sub-complete-repo
        shell: bash       
        run: |
          ls -ltr
          git submodule deinit git-sub-module         
          rm -f .gitmodules          
          ls -ltr
          cd git-sub-module
          ls -ltr
          echo "Setting remote add"
          git remote add adobe https://github.com/sudarsana-reddy/github-with-sub-complete-repo.git
          # echo "set username"
          # git config credential.username sudarsana.ala@gmail.com
          # echo "set password"
          # git config credential.helper "!echo password=${{ secrets.TOKEN }}; echo"
          echo "show remote urls"
          git remote -v
          echo "checking out main"
          git checkout main
          echo "pull the chages"
          git pull
          echo "git status"
          git status
          echo "prune the remote"
          git fetch adobe --prune
          echo "check local git issues"
          git fsck --full
          echo "push the changes to remote"
          git remote set-url --push adobe "https://sudarsana-reddy:${{ secrets.PAT }}@github.com/sudarsana-reddy/github-with-sub-complete-repo.git"
          git push -u adobe main --force
    
      - name: build
        shell: bash
        run: |
          # TOKEN=${{ secrets.PAT }}
          # git -c submodule.git-sub-module.url=https://$TOKEN@github.com/sudarsana-reddy/git-sub-module.git submodule update --init --recursive
          mvn -B verify --file pom.xml
