name: Test git submodule

on:
  workflow_dispatch:

permissions: 
  contents: write
  id-token: write   

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
    
    
      - name: build
        shell: bash
        run: |
          PASSWORD=${{ secrets.GITLAB_TOKEN }}
          USERNAME=sreddy240
          git submodule set-url gitlab-sub-module https://$USERNAME:$PASSWORD@gitlab.com/sudarsana-reddy/gitlab-sub-module
          git submodule update --init
          mvn -B verify --file pom.xml
