name: Test git submodule

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.PAT }}

      - name: build
        shell: bash
        env:
          PAT: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git submodule init
          git submodule update
          mvn -B verify --file pom.xml
       
